global:
  domain: argo.divanchik.m1xxos.online

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  httproute:
    enabled: true
    parentRefs:
      - name: divanchik-gateway
        namespace: gwin
        sectionName: https

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2
